### ISSUE TITLE
Github Action for Terraform Checks

### ISSUE THREAD

**Issue by eddie-knight** [finos/compliant-financial-infrastructure#124]
### Description of Problem:
When modifying existing terraform code, automated checks should run to verify that code is written as intended, and (eventually) to validate that the code produces the expected results.

### Potential Solutions:
There are two approaches to using Github Actions that I'd like the team to consider. I can take initiative in creating either of these solutions, but I'd like the team to agree on the approach before I start working on it.

As pretext, remember that (even when using modules) the actual checks will need to be run against each terraform config- which requires the execution to be done within the specific directory housing the config. This means our CI will need to explicitly state the directory that it is running checks against.

:x: 0) [Non-option] We could technically create a large single workflow that is extended each time new terraform is added, and it will run checks against every directory every time. This is less than ideal in general, but it is _out of the question_ if we intend to add post-deployment validation checks.

✅  **Now and achievable** 👉🏻  1) We could repeat code between multiple files. This will be clear and easy to understand without needing additional documentation, but the code will be repeated across each workflow. Also, any change will need to be done in multiple places, creating a higher need for active drift management between the workflows over time.

:x: 2) We could take [this githooks approach](https://medium.com/citihub/using-githooks-to-dry-out-github-actions-17ae72e7985d) that I've used in the past. It will require some additional documentation to onboard anyone contributing to the workflows, but it will allow for all common code to be maintained in a single location that is then populated across all applicable workflows. It's also really quick to maintain (once you understand what's it's doing).

✅  **Later** 👉🏻  3) @TLATER 's approach - Write a custom GitHub Action using GitHub's JavaScript API that creates rules that adapt to the sub directories. GitHooks (2) affect @TLATER's, and potentially other's, code configuration.

**Comment by eddie-knight** [comment]
Relates to #117 - That issue is specific to terraform FMT, while the discussion here will pertain to all checks (including fmt)

**Comment by mcleo-d** [comment]
Hi @eddie-knight,

I have extended CSC Sprint 2 until 17th June '21 due to team member annual leave and have added this item to the #127 agenda to discuss in relation to completion and Sprint 3.

Cheers,

James 🚀

**Comment by eddie-knight** [comment]
@TLATER Could you put together a spec or a PR to demonstrate your proposed solution?

**Comment by TLATER** [comment]
I responded on call previously, but yes, it's in progress :)

**Comment by TLATER** [comment]
I'm sadly just not finding enough time for contributions here at the moment :( I think it makes sense to go ahead with what exists and is working in absence of a counter proposal.

**Comment by mcleo-d** [comment]
@eddie-knight - Please take a note of the decision that was made on call #131 to go with option's 1 and 3. Do you have examples of these items?

**Comment by mcleo-d** [comment]
## Definition of Done

A working example of the following within the code repository

> ✅ Now and achievable 👉🏻 1) We could repeat code between multiple files. This will be clear and easy to understand without needing additional documentation, but the code will be repeated across each workflow. Also, any change will need to be done in multiple places, creating a higher need for active drift management between the workflows over time.

**Comment by eddie-knight** [comment]
RE: @mcleo-d 
> Please take a note of the decision that was made on call #131 to go with option's 1 and 3. Do you have examples of these items?

---
Sure! I threw together an example workflow that I <i>slightly</i> adjusted to get it <i>close</i> to what this repo may need.

The example comes from a repo where we were using a tf backend to manage statefiles, which will need some customized attention. A first version could exclude the `terraform init` and `terraform validate` steps to avoid managing state initially.

<details><summary>Example
</summary><p>

```yaml
name: "Verify Azure Postgres Terraform"

on:
  pull_request:
    paths:
      - ".github/workflows/azure-postgres-verify.yml"
      - "azure/postgresql/terraform/*"
      - "azure/postgresql/terraform/modules/postgres/*"

jobs:
  validate:
    name: "Validate Terraform"
    runs-on: ubuntu-latest
    env:
      # example
      # TF_BACKEND_KEY: dev.aks_configure.terraform.tfstate

    defaults:
      run:
        shell: bash
        working-directory: azure/postgresql/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform Environment
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.5
          # example
          # cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        continue-on-error: true
        run:
          echo example
          # terraform init -lock=false \
          #   -backend-config="resource_group_name=terraform" \
          #   -backend-config="key=${{ env.TF_BACKEND_KEY }}" \
          #   -backend-config="access_key=${{ secrets.TF_BACKEND_ACCESS_KEY }}" \
          #   -backend-config="storage_account_name=${{ secrets.TF_BACKEND_SA }}"

      - name: Terraform Validate
        id: validate
        if: github.event_name == 'pull_request'
        run: terraform validate -no-color
        continue-on-error: true

      - name: Create PR comment with check results
        uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request' && (steps.fmt.outcome == 'failure' || steps.init.outcome == 'failure' || steps.validate.outcome == 'failure')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `### Result from failed workflow: ${{ github.workflow }}
            #### Terraform Format and Style :pencil2: \`${{ steps.fmt.outcome }}\`

            #### Terraform Initialization :gear:\`${{ steps.init.outcome }}\`

            #### Terraform Validate :interrobang:\`${{ steps.validate.outcome }}\`
            
            *Pusher: @${{ github.actor }}, Action: ${{ github.event_name }}*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Exit based on status of fmt, init, and validate
        if: steps.fmt.outcome == 'failure' || steps.init.outcome == 'failure' || steps.validate.outcome == 'failure'
        run: |
          echo Init: ${{ steps.init.outcome }}
          echo Format: ${{ steps.fmt.outcome }}
          echo Validate: ${{ steps.validate.outcome }}
          exit 1
```

</p></details>

Some optional stuff in there is in the `id` and `if` logic. 

The exit step will use those to print the result summary to the workflow log. 

And if you want to include it... the preceding _comment_ step will produce a comment on the PR that looks like this:
![image](https://user-images.githubusercontent.com/21176439/125824315-7f4e3622-8a96-4f96-89df-961a4b6f0edb.png)

**Comment by eddie-knight** [comment]
In case it's easier to read....
<details><summary>Here is the same example as above, but with some of the optional items removed.
</summary><p>

```yaml
name: "Verify Azure Postgres Terraform"

on:
  pull_request:
    paths:
      - ".github/workflows/azure-postgres-verify.yml"
      - "azure/postgresql/terraform/*"
      - "azure/postgresql/terraform/modules/postgres/*"

jobs:
  validate:
    name: "Validate Terraform"
    runs-on: ubuntu-latest
    env:
      # example
      # TF_BACKEND_KEY: dev.aks_configure.terraform.tfstate

    defaults:
      run:
        shell: bash
        working-directory: azure/postgresql/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform Environment
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.5
          # example
          # cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run:
          echo example
          # terraform init -lock=false \
          #   -backend-config="resource_group_name=terraform" \
          #   -backend-config="key=${{ env.TF_BACKEND_KEY }}" \
          #   -backend-config="access_key=${{ secrets.TF_BACKEND_ACCESS_KEY }}" \
          #   -backend-config="storage_account_name=${{ secrets.TF_BACKEND_SA }}"

      - name: Terraform Validate
        if: github.event_name == 'pull_request'
        run: terraform validate -no-color
        continue-on-error: true
```

</p></details>

Let me know how else you'd like me to help move things forward.
